name: Release

on:
  push:
    branches:
      - master
      - next

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '24'

      - name: Install dependencies
        run: mix deps.get

      - name: Run Credo linter
        run: mix credo --strict

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: paulhatch/semantic-version@v5.3.0
        id: version

      - uses: softprops/action-gh-release@v2
        id: create_release
        with:
          generate_release_notes: "true"
          name: v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Write version to file
        run: mkdir -p .release && echo "${{ steps.version.outputs.version }}" > .release/version

      - name: Commit and push version file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .release/version
          # Only commit if there are staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(release): update version to ${{ steps.final_version.outputs.version }}"
            git push
          fi

      - name: Build and push Docker images
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${{ github.ref_name }}"
          fi
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} \
            -t ghcr.io/${{ github.repository }}:${DOCKER_TAG} \
            --push .